"""Added 'datetime' field to 'Hangout'.

Revision ID: 266b294905f7
Revises: 0d9c5f34e873
Create Date: 2024-08-21 03:15:49.168721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266b294905f7'
down_revision = '0d9c5f34e873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hangout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hangout', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
