"""Added friend request relationship to 'User'.

Revision ID: 72f45228b9bf
Revises: 265803533b7d
Create Date: 2024-08-19 16:25:35.953365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f45228b9bf'
down_revision = '265803533b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hangout_attendee', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_hangoutattendee_id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hangout_attendee', schema=None) as batch_op:
        batch_op.drop_constraint('unique_hangoutattendee_id', type_='unique')

    # ### end Alembic commands ###
