"""Updated UUID logic, added 'name' column to 'Hangout' table

Revision ID: c68d758fc688
Revises: bebe84a5fe1d
Create Date: 2024-08-05 17:23:05.860421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68d758fc688'
down_revision = 'bebe84a5fe1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hangout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hangout', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
